[env]
python = "3.8"  # Specify your desired Python version

[tools]
python = "3.8"

[plugins]
python = "https://github.com/asdf-community/asdf-python.git"

[tasks]
install_dependencies = "pip install -r requirements.txt"

[settings]
# Optional settings, for example, if you want to automatically answer yes to all prompts
yes = true
